export enum PageRoutes {
  HOME = "/",
  LOGIN = "/login",
  SIGNUP = "/signup",
  DASHBOARD = "/dashboard",
  PRODUCT_OVERVIEW = "/product-overview",
  PRODUCT_LIST = "/product-list",
  PRODUCT_TRANSACTION = "/product-transaction",
  CUSTOMER_OVERVIEW = "/customer-overview",
  CUSTOMER_LIST = "/customer-list",
  AI_MARKETING = "/ai-marketing",
  ANALYTICS = "/analytics",
  ACCOUNT = "/account",
  SETTINGS = "/settings",
}